name: 'Bybloo!'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86551
title: 'Bybloo!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3e3e'
    - '#161616'
    - '#e4e4e4'
    - '#595959'
    - '#a7a7a7'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
