name: 'Bybloo!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8497145322617143
title: 'Bybloo!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f7fc'
    - '#cbc1c9'
    - '#452f37'
    - '#1754b7'
    - '#ff2c85'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
