layout_spectrum: 0.6606662205886096
typography_spectrum: 0.29642187245190144
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.1364999630022794
  lightness: 0.14869755692780018
  saturation: 0.04265438439324498
  rhythmicContrast: 0.9900499198120087
coverPrefs:
  filter: false
name: Bybloo!
favicon: null
title: Bybloo!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
